### ISSUE TITLE
something wrong when i run  train.py in avenue dataset

### ISSUE THREAD

**Issue by zhouwei342622** [StevenLiuWen/ano_pred_cvpr2018#45]
i successfully run train.py in ped1 and ped2 datasets.but when i try to run train.py in avenue and shanghai tech datasets .there have been some errors as follows .and i don't know how to solve it .Could you help me ?Thank you (because of they are color dataset?)

Traceback (most recent call last):

  File "/home/cvzw/anaconda3/envs/ALOCC-CVPR2018-master/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 209, in __call__
    ret = func(*args)

  File "/home/cvzw/anaconda3/envs/ALOCC-CVPR2018-master/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 514, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/home/cvzw/PycharmProjects/zhouwei/future frame prediction/Codes/utils.py", line 54, in video_clip_generator
    video_clip.append(np_load_frame(video_info['frame'][frame_id], resize_height, resize_width))

  File "/home/cvzw/PycharmProjects/zhouwei/future frame prediction/Codes/utils.py", line 24, in np_load_frame
    image_resized = cv2.resize(image_decoded, (resize_width, resize_height))

cv2.error: /io/opencv/modules/imgproc/src/imgwarp.cpp:3492: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize

**Comment by zachluo** [comment]
@zhouwei342622 It should be the case that image_decoded returns None. Please provide more details.
