### ISSUE TITLE
training error about flownet

### ISSUE THREAD

**Issue by shamoqianting** [StevenLiuWen/ano_pred_cvpr2018#8]
Dear Dr. LiuWen,
I am trying to train from scratch following your instruction. But I encountered the following error:

`Traceback (most recent call last):
  File "train.py", line 94, in <module>
    height=flow_height, width=flow_width, reuse=None)
  File "/data1/ShanghaiTech-FutureFramePred/ano_pred_cvpr2018-master/Codes/models.py", line 25, in flownet
    net = FlowNetSD(mode=Mode.TEST)
TypeError: Can't instantiate abstract class FlowNetSD with abstract methods loss
`

Could you help to check this ? Thank you very much

**Comment by shamoqianting** [comment]
It seems that the error caused by a missing method "loss" which should be overridden in **Codes/flownet2/src/flownet_sd/flownet_sd.py** .
I just uncommentted the loss function and the program began to run, although I am not sure the result is correct or not.
